name: pdf_render
description: A plugin that provides you with intermediate PDF rendering APIs and
  easy-to-use Flutter Widgets.
version: 1.4.12
homepage: https://github.com/espresso3389/flutter_pdf_render

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.2
  plugin_platform_interface: ^2.1.8
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: jp.espresso3389.pdf_render
        pluginClass: PdfRenderPlugin
      ios:
        pluginClass: PdfRenderPlugin
      macos:
        pluginClass: SwiftPdfRenderPlugin
      web:
        pluginClass: PdfRenderWebPlugin
        fileName: src/web/pdf_render_web_plugin.dart
